version: '2'
services:
  nginx:
    image: nginx
    ports:
      - 80:80
    links:
      - fpm
    volumes:
      - ../web/baba:/var/www/web
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  fpm:
    build: php-fpm/
    links:
      - mysql
    volumes:
      - ../web/baba:/var/www/web
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: dev_symfony
      MYSQL_USER: dev_user
      MYSQL_PASSWORD: dev_pass
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/data:/var/lib/mysql
  symfony:
    links:
      - fpm
      - mysql
    build: symfony/
    volumes: 
      - ../web/baba:/var/www/web
    tty: true
